// Generated by CoffeeScript 2.3.2
(function() {
  var contenders, number, square;

  number = 42;

  square = function(x) {
    return x * x;
  };

  contenders = ["liuxiang", "yaoming"];

  console.log(contenders);

}).call(this);

()=>{
  
}